### ISSUE TITLE
Device local proxy exiting after first stream is terminated 

### ISSUE THREAD

**Issue by rezasherafat** [Azure-Samples/azure-iot-samples-csharp#40] opened 2019-02-13 20:20 UTC
See [link](https://github.com/Azure-Samples/azure-iot-samples-csharp/issues/31)

**Comment by ewertons** [comment] 2019-02-13 22:01
To give some insight here, during private preview the DeviceClient had a callback-based handler for streaming requests. In that case the handler would be called as many times as requests arrived, so this scenario worked fine.
For public preview the callbacks were removed and replaced with the Task-based WaitForDeviceStreamingRequestAsync, which returns after 1 request is received.

The sample must be updated to have a loop calling WaitForDeviceStreamingRequestAsync over and over.

**Comment by jenoola** [comment] 2019-03-07 23:24
Duplicate of #31

**Closed by jenoola** 2019-03-07 23:24 UTC
